services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
  user_service:
    build: ./backend/user_service
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017
    ports:
      - "8001:8000"
  auth_service:
    build: ./backend/auth_service
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017
    ports:
      - "8002:8000"
  celery_worker:
    build: ./celery_worker
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
  frontend:
    build: ./frontend
    ports:
      - "5173:5173" 