services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_monolith_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/.env:/app/.env
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: fastapi_monolith_db
    command: ["--quiet", "--logpath=/dev/null"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_vite_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - app
    environment:
      - DOCKER_RUN=${DOCKER_RUN}

volumes:
  mongo_data:
    driver: local 